import type { Metadata } from "next";
import ".././globals.css";
import { Header } from "@/app/shared/ui/Header";
import { Footer } from "../shared/ui/Footer";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Kalita - Developement Website",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <Providers>
        <body>
          <Header />
          {children}
          <Footer /> 
        </body>
      </Providers>
    </html>
  );
}
