import type { Metadata } from "next";
import "../../globals.css";
import { Sidebar } from "@/domain/dashboard/components/Sidebar";

export const metadata: Metadata = {
  title: "Kalita - Developement Website",
  description: "Generated by create next app",
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
